# Generated by Django 3.2 on 2021-05-01 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210501_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_alternative',
            options={'verbose_name': 'Product Alternative', 'verbose_name_plural': 'Product Alternatives'},
        ),
        migrations.CreateModel(
            name='Product_Accessoires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCAlternative', models.ManyToManyField(related_name='accessories_product', to='product.Product')),
                ('PACCProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessories_product', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Accessory',
                'verbose_name_plural': 'Product Accessories',
            },
        ),
    ]
