# Generated by Django 3.2 on 2021-05-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210501_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATdesc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATimg',
            field=models.ImageField(upload_to='category/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATname',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATparent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATparent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='product_accessoires',
            name='PACCAlternative',
            field=models.ManyToManyField(related_name='accessories_product', to='product.Product', verbose_name='Accessories'),
        ),
        migrations.AlterField(
            model_name='product_accessoires',
            name='PACCProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessories_product', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALNAlternative',
            field=models.ManyToManyField(related_name='alternative_product', to='product.Product', verbose_name='Alternatives'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALNProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product', verbose_name='Product'),
        ),
    ]
