# Generated by Django 3.2 on 2021-05-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210508_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDIsBestSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDIsNew',
            field=models.BooleanField(default=True),
        ),
    ]
